openapi: 3.0.1
info:
  title: 'Alerts API'
  description: 'API for managing alerts.'
  version: '1.0.0'
servers:
  - url: 'http://api.structuredlabs.com'
security:
  - bearerAuth: []

paths:
  /alerts:
    post:
      summary: Create an alert
      requestBody:
        description: Alert configuration details.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveScheduleApiRequest'
      responses:
        '200':
          description: Successful response from server.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateAlertResponse'

    get:
      summary: Get all alerts configured
      parameters:
        - name: alertId
          in: query
          schema:
            type: string
        - name: workspaceId
          in: query
          required: true
          schema:
            type: string
        - name: userId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved the alert.
          content:
            application/json:
              schema:
                type: object
                properties:
                  schedules:
                    type: array
                    items:
                      $ref: '#/components/schemas/Schedule'

    delete:
      summary: Delete a schedule
      parameters:
        - in: query
          name: userId
          required: true
          schema:
            type: string
          description: ID of the user
        - in: query
          name: scheduleId
          required: true
          schema:
            type: string
          description: ID of the schedule
        - in: query
          name: workspaceId
          required: true
          schema:
            type: string
          description: ID of the workspace
      responses:
        '200':
          description: Schedule deletion response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteAlertScheduleResponse'
        '400':
          description: Bad Request

  /alerts/trigger:
    post:
      summary: Trigger an alert
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                scheduleId:
                  type: string
                workspaceId:
                  type: string
      responses:
        '200':
          description: Successfully triggered the alert.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sucess:
                    type: boolean
                  alert:
                    $ref: '#/components/schemas/Alert'

  /alerts/history:
    get:
      summary: View alert history
      responses:
        '200':
          description: Successfully retrieved alert history.
          content:
            application/json:
              schema:
                type: object
                properties:
                  alerts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Alert'

    delete:
      summary: Deletes an alert from history
      parameters:
        - name: alertId
          in: query
          required: true
          schema:
            type: string
        - name: workspaceId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully cleared all alert history.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string

components:
  schemas:
    Error:
      required:
        - error
        - message
      type: object
      properties:
        error:
          type: integer
          format: int32
        message:
          type: string
    SeverityStateEnum:
      type: string
      enum:
        - High
        - Medium
        - Low
        - Info
    FREQUENCY_ENUM:
      type: string
      enum:
        - Daily
        - Weekly
        - "Doesn't repeat"
    TIMEZONE_ENUM:
      type: string
      enum:
        - America/Los_Angeles
        - America/New_York
        - Europe/London
    ScheduleConf:
      type: object
      properties:
        timezone:
          $ref: '#/components/schemas/TIMEZONE_ENUM'
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
        time:
          type: string
          example: '12:00'
        frequency:
          $ref: '#/components/schemas/FREQUENCY_ENUM'
    Schedule:
      type: object
      properties:
        name:
          type: string
        user_id:
          type: string
        metric:
          type: string
        schedule:
          $ref: '#/components/schemas/ScheduleConf'
        severity:
          $ref: '#/components/schemas/SeverityStateEnum'
        workspaceId:
          type: string
        slack_enabled:
          type: boolean
        email_enabled:
          type: boolean
        assigned_emails:
          type: array
          items:
            type: string
            format: email
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        next_run_at:
          type: string
          format: date-time
        ownerUserId:
          type: string
    SaveScheduleApiRequest:
      type: object
      properties:
        schedule:
          $ref: '#/components/schemas/Schedule'
    CreateAlertResponse:
      type: object
      properties:
        success:
          type: boolean
        scheduleId:
          type: string
    DeleteAlertScheduleApiRequest:
      type: object
      properties:
        userId:
          type: string
        scheduleId:
          type: string
        workspaceId:
          type: string
    DeleteAlertScheduleResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    Alert:
      type: object
      properties:
        source:
          type: string
        alertId:
          type: string
        severity:
          $ref: '#/components/schemas/SeverityStateEnum'
        time:
          type: string
        alertName:
          type: string
        description:
          type: string
        status:
          type: string
        workspaceId:
          type: string
        userId:
          type: string
        ownerUserId:
          type: string    
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  