openapi: 3.0.1
info:
  title: Metrics API
  description: API for managing metrics and segments
  version: 1.0.0
servers:
  - url: 'http://api.structuredlabs.com'
security:
  - bearerAuth: []
paths:
  /metrics/compute:
    post:
      summary: Compute a Metric
      description: >-
        Computes a predefined or custom metric using data from the entire
        Harbor.
      operationId: computeMetric
      requestBody:
        description: Details required to compute the metric.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                metric:
                  type: string
                  description: The metric to compute.
                userId:
                  type: string
                  description: The user ID for the metric computation.
                workspaceId:
                  type: string
                  description: The workspace ID for the metric computation.
      responses:
        '200':
          description: Successfully computed the metric.
          content:
            application/json:
              schema:
                type: object
                properties:
                  metric:
                    type: string
                    description: The computed metric.
                  value:
                    type: number
                    description: The computed value of the metric.
                  raw_data:
                    type: object
                    description: The raw data used for the computation.
                  status:
                    type: string
                  message:
                    type: string

  /metrics/checkPrerequisite:
    post:
      summary: Check Prerequisite
      description: >-
        Checks if the prerequisites for a metric computation are met.
      operationId: checkPrerequisite
      requestBody:
        description: Details required to check the prerequisites.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nodeType:
                  type: string
                  description: The node type for the metric computation.
                userId:
                  type: string
                  description: The user ID for the metric computation.
                workspaceId:
                  type: string
                  description: The workspace ID for the metric computation.
      responses:
        '200':
          description: Successfully checked the prerequisites.
          content:
            application/json:
              schema:
                type: object
                properties:
                  exists:
                    type: boolean
                  success:
                    type: boolean
                  
components:
  schemas:
    Error:
      required:
        - error
        - message
      type: object
      properties:
        error:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
