openapi: 3.0.1
info:
  title: Queries API
  description: API for managing queries and query threads.
  version: 1.0.0
servers:
  - url: 'http://api.structuredlabs.com'
security:
  - bearerAuth: []
paths:
  /queries:
    post:
      summary: Create a New Query Thread
      description: Initiates a new query thread.
      operationId: createQueryThread
      requestBody:
        description: Details of the query to initialize.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                # { query, type, createdBy, userId, queryTitle, id, workspaceId }
                query:
                  type: string
                  description: The text of the query to execute.
                type:
                  type: string
                  description: The type of query to execute.
                createdBy:
                  type: string
                  description: The user who created the query.
                userId:
                  type: string
                  description: The user ID of the user who created the query.
                queryTitle:
                  type: string
                  description: The title of the query.
                id:
                  type: string
                  description: The unique identifier for the query.
                workspaceId:
                  type: string
                  description: The workspace ID for the query.
                  
      responses:
        '201':
          description: Successfully created a new query thread.
          content:
            application/json:
              schema:
                type: object
                properties:
                  # {
                  #   id: id,
                  #   query,
                  #   type,
                  #   createdBy,
                  #   createdAt: createdAt,
                  #   status: "created",
                  #   userId: userId,
                  #   queryTitle: queryTitle,
                  #   workspaceId: workspaceId,
                  # }
                  id:
                    type: string
                  query:
                    type: string
                  type:
                    type: string
                  createdBy: 
                    type: string
                  createdAt:
                    type: string
                  status: 
                    type: string
                  userId:
                    type: string
                  queryTitle:
                    type: string
                  workspaceId:
                    type: string

  /queries/delete:
    delete:
      summary: Delete a Query Thread
      description: Deletes the specified query thread.
      operationId: deleteQueryThread
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
        - name: workspaceId
          in: query
          required: true
          schema:
            type: string
        - name: queryId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted the query thread.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /queries/history:
    get:
      summary: Get Query History
      description: Retrieves the history of queries for the specified user.
      operationId: getQueryHistory
      parameters:
        - name: userId
          in: query
          required: true
          schema:
            type: string
        - name: workspaceId
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved the query history.
          content:
            application/json:
              schema:
                type: object
                properties:
                  queries:
                    type: array
                    items:
                      type: object

  /queries/run:
    post:
      summary: Run a Query
      description: Executes the specified query.
      operationId: runQuery
      requestBody:
        description: Details of the query to execute.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                # {  userId,  workspaceId,  queryId,  queryText,  queriesTypeMode,  selectedQuery,}
                userId:
                  type: string
                  description: The user ID of the user who created the query.
                workspaceId:
                  type: string
                  description: The workspace ID for the query.
                queryId:
                  type: string
                  description: The unique identifier for the query.
                queryText: 
                  type: string
                  description: The text of the query to execute.
                queriesTypeMode:
                  type: string
                  description: The type of query to execute.
                selectedQuery:
                  type: string
                  description: The title of the query.
      responses:
        '200':
          description: Successfully executed the query.
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: object
                    properties:
                      echart:
                        type: object
                      dataPreview:
                        type: array
                        items:
                          type: object
                      queryPreview:
                        type: string

components:
  schemas:
    Error:
      required:
        - error
        - message
      type: object
      properties:
        error:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
